In [12]:
import pandas as pd
import pandas_datareader.data as web
import datetime

#DATA_SOURCE = "morningstar"
DATA_SOURCE = "google"

start = datetime.datetime(2016,1,1)
end = datetime.date.today()

apple = web.DataReader("SPY", DATA_SOURCE, start, end)

type(apple)
apple

C:\Users\wanghh\Anaconda3\lib\site-packages\pandas_datareader\google\daily.py:40: UnstableAPIWarning:
The Google Finance API has not been stable since late 2017. Requests seem
to fail at random. Failure is especially common when bulk downloading.

  warnings.warn(UNSTABLE_WARNING, UnstableAPIWarning)

              Open    High     Low   Close     Volume
Date
2016-01-04  200.49  201.03  198.59  201.02  218722198
2016-01-05  201.40  201.90  200.05  201.36  110845849
2016-01-06  198.34  200.06  197.60  198.82  152112604
2016-01-07  195.33  197.44  193.59  194.05  213436073
2016-01-08  195.19  195.85  191.58  191.92  209817228
2016-01-11  193.01  193.41  189.82  192.11  187941323
2016-01-12  193.82  194.55  191.14  193.66  172330490
2016-01-13  194.45  194.86  188.38  188.83  218780219
2016-01-14  189.55  193.26  187.66  191.93  237705564
2016-01-15  186.77  188.76  185.52  187.81  317904944
2016-01-19  189.96  190.11  186.20  188.06  192723808
2016-01-20  185.03  187.50  181.02  185.65  283288870
2016-01-21  186.21  188.87  184.64  186.69  191085235
2016-01-22  189.78  190.76  188.88  190.52  166679398
2016-01-25  189.92  190.15  187.41  187.64  127112162
2016-01-26  188.42  190.53  188.02  190.20  138004751
2016-01-27  189.58  191.56  187.06  188.13  184186327
2016-01-28  189.96  190.20  187.16  189.11  142851654
2016-01-29  190.02  193.88  189.88  193.72  204034161
2016-02-01  192.53  194.58  191.84  193.65  133582159
2016-02-02  191.96  191.97  189.54  190.16  175500039
2016-02-03  191.41  191.78  187.10  191.30  204060878
2016-02-04  190.71  192.75  189.96  191.60  137261874
2016-02-05  190.99  191.67  187.20  187.95  178436180
2016-02-08  185.77  186.12  182.80  185.42  189248416
2016-02-09  183.36  186.94  183.20  185.43  179281791
2016-02-10  186.41  188.34  185.12  185.27  146910485
2016-02-11  182.34  184.10  181.09  182.86  214629542
2016-02-12  184.96  186.65  183.96  186.63  127093730
2016-02-16  188.77  189.81  187.63  189.78  115542766
...            ...     ...     ...     ...        ...
2017-12-20  268.27  268.33  266.69  267.03   76751500
2017-12-21  267.74  268.38  267.30  267.58   67032339
2017-12-22  267.60  267.64  266.90  267.51   78720873
2017-12-26  267.05  267.44  266.88  267.19   45244433
2017-12-27  267.38  267.73  267.01  267.32   57750986
2017-12-28  267.89  267.92  267.45  267.87   45116139
2017-12-29  268.53  268.55  266.64  266.86   96007424
2018-01-02  267.84  268.81  267.40  268.77   86655749
2018-01-03  268.96  270.64  268.96  270.47   90070416
2018-01-04  271.20  272.16  270.54  271.61   80636408
2018-01-05  272.51  273.56  271.95  273.42   83523995
2018-01-08  273.31  274.10  272.98  273.92   57319192
2018-01-09  274.40  275.25  274.08  274.54   57253957
2018-01-10  273.68  274.42  272.92  274.12   69574318
2018-01-11  274.75  276.12  274.56  276.12   62361455
2018-01-12  276.42  278.11  276.08  277.92   90816076
2018-01-16  279.35  280.09  276.18  276.97  106555142
2018-01-17  278.03  280.05  276.97  279.61  113258799
2018-01-18  279.48  279.96  278.58  279.14  100728006
2018-01-19  279.80  280.41  279.14  280.41  140920098
2018-01-22  280.17  282.69  280.11  282.69   91322408
2018-01-23  282.74  283.62  282.37  283.29   97084700
2018-01-24  284.02  284.70  281.84  283.18  134816117
2018-01-25  284.16  284.27  282.40  283.30   84587313
2018-01-26  284.25  286.63  283.96  286.58  107743119
2018-01-29  285.93  286.43  284.50  284.68   90118337
2018-01-30  282.60  284.74  281.22  281.76  131796419
2018-01-31  282.73  283.30  280.68  281.90  118948131
2018-02-01  281.07  283.06  280.68  281.58   90102470
2018-02-02  280.08  280.23  275.41  275.45  173174790

[526 rows x 5 columns]